"""
Base de datos local de packages Android conocidos (~400 entradas).
Cubre AOSP, MIUI/HyperOS, Google, MediaTek y apps populares.
Complementa apps_catalog.py (que cubre apps debloateables del wizard).
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class KnownPackage:
    name: str
    category: str  # "Sistema Android" | "Sistema Xiaomi" | "Google" | ...


_A = "Sistema Android"
_X = "Sistema Xiaomi"
_G = "Google"
_S = "Redes sociales"
_C = "Comunicación"
_E = "Entretenimiento"
_P = "Productividad"
_M = "MediaTek"

PACKAGES_DB: dict[str, KnownPackage] = {

    # ─── Sistema Android (AOSP) ──────────────────────────────────────────────
    "android":                                      KnownPackage("Android System",              _A),
    "com.android.server.telecom":                   KnownPackage("Telefonía del sistema",       _A),
    "com.android.phone":                            KnownPackage("Gestor de llamadas",          _A),
    "com.android.settings":                         KnownPackage("Configuración",               _A),
    "com.android.systemui":                         KnownPackage("Interfaz del sistema",        _A),
    "com.android.launcher3":                        KnownPackage("Launcher AOSP",               _A),
    "com.android.keychain":                         KnownPackage("Cadena de claves",            _A),
    "com.android.providers.settings":               KnownPackage("Proveedor de ajustes",        _A),
    "com.android.providers.contacts":               KnownPackage("Proveedor de contactos",      _A),
    "com.android.providers.media":                  KnownPackage("Proveedor multimedia",        _A),
    "com.android.providers.media.module":           KnownPackage("Módulo multimedia",           _A),
    "com.android.providers.downloads":              KnownPackage("Gestor de descargas",         _A),
    "com.android.providers.calendar":               KnownPackage("Proveedor de calendario",     _A),
    "com.android.providers.telephony":              KnownPackage("Proveedor de telefonía",      _A),
    "com.android.providers.blockednumber":          KnownPackage("Números bloqueados",          _A),
    "com.android.providers.userdictionary":         KnownPackage("Diccionario de usuario",      _A),
    "com.android.contacts":                         KnownPackage("Contactos AOSP",              _A),
    "com.android.dialer":                           KnownPackage("Marcador AOSP",               _A),
    "com.android.mms":                              KnownPackage("Mensajes SMS AOSP",           _A),
    "com.android.camera2":                          KnownPackage("Cámara AOSP",                 _A),
    "com.android.gallery3d":                        KnownPackage("Galería AOSP",                _A),
    "com.android.filemanager":                      KnownPackage("Gestor de archivos",          _A),
    "com.android.calculator2":                      KnownPackage("Calculadora AOSP",            _A),
    "com.android.calendar":                         KnownPackage("Calendario AOSP",             _A),
    "com.android.deskclock":                        KnownPackage("Reloj / Alarmas AOSP",        _A),
    "com.android.email":                            KnownPackage("Email AOSP",                  _A),
    "com.android.browser":                          KnownPackage("Navegador AOSP",              _A),
    "com.android.music":                            KnownPackage("Música AOSP",                 _A),
    "com.android.bluetooth":                        KnownPackage("Bluetooth",                   _A),
    "com.android.bluetooth.map":                    KnownPackage("Bluetooth MAP",               _A),
    "com.android.nfc":                              KnownPackage("NFC",                         _A),
    "com.android.wifi":                             KnownPackage("WiFi",                        _A),
    "com.android.wifi.resources":                   KnownPackage("Recursos WiFi",               _A),
    "com.android.carrierconfig":                    KnownPackage("Config operadora",            _A),
    "com.android.stk":                              KnownPackage("SIM Toolkit",                 _A),
    "com.android.packageinstaller":                 KnownPackage("Instalador de paquetes",      _A),
    "com.android.defcontainer":                     KnownPackage("Contenedor de instalación",   _A),
    "com.android.backupconfirm":                    KnownPackage("Confirmación de backup",      _A),
    "com.android.certinstaller":                    KnownPackage("Instalador de certificados",  _A),
    "com.android.inputdevices":                     KnownPackage("Dispositivos de entrada",     _A),
    "com.android.managedprovisioning":              KnownPackage("Provisión gestionada",        _A),
    "com.android.printspooler":                     KnownPackage("Cola de impresión",           _A),
    "com.android.wallpaper":                        KnownPackage("Fondos de pantalla",          _A),
    "com.android.wallpaperbackup":                  KnownPackage("Backup de fondos",            _A),
    "com.android.dreams.basic":                     KnownPackage("Salvapantallas básico",       _A),
    "com.android.dreams.phototable":                KnownPackage("Salvapantallas fotos",        _A),
    "com.android.emergency":                        KnownPackage("Información de emergencia",   _A),
    "com.android.captiveportallogin":               KnownPackage("Portal cautivo",              _A),
    "com.android.companiondevicemanager":           KnownPackage("Dispositivos compañero",      _A),
    "com.android.documentsui":                      KnownPackage("UI de documentos",            _A),
    "com.android.ext.services":                     KnownPackage("Servicios extendidos",        _A),
    "com.android.htmlviewer":                       KnownPackage("Visor HTML",                  _A),
    "com.android.location.fused":                   KnownPackage("Ubicación fusionada",         _A),
    "com.android.messaging":                        KnownPackage("Mensajes AOSP",               _A),
    "com.android.nearby":                           KnownPackage("Nearby Share AOSP",           _A),
    "com.android.permissioncontroller":             KnownPackage("Control de permisos",         _A),
    "com.android.safetycenter":                     KnownPackage("Centro de seguridad",         _A),
    "com.android.shell":                            KnownPackage("Shell Android",               _A),
    "com.android.soundrecorder":                    KnownPackage("Grabadora de voz",            _A),
    "com.android.speechrecorder":                   KnownPackage("Grabación de voz",            _A),
    "com.android.storagemanager":                   KnownPackage("Gestor de almacenamiento",    _A),
    "com.android.traceur":                          KnownPackage("Rastreador del sistema",      _A),
    "com.android.tethering":                        KnownPackage("Anclaje a red",               _A),
    "com.android.vpndialogs":                       KnownPackage("Diálogos VPN",                _A),
    "com.android.hotspot2.osulogin":                KnownPackage("Login Hotspot 2.0",           _A),
    "com.android.simappdialog":                     KnownPackage("Diálogo SIM",                 _A),
    "com.android.statementservice":                 KnownPackage("Servicio de declaraciones",   _A),
    "com.android.mtp":                              KnownPackage("Protocolo MTP",               _A),
    "com.android.modulemetadata":                   KnownPackage("Metadatos de módulos",        _A),
    "com.android.ons":                              KnownPackage("Servicio de red ONS",         _A),
    "com.android.carrierdefaultapp":                KnownPackage("App operadora por defecto",   _A),
    "com.android.cellbroadcastreceiver":            KnownPackage("Alertas de emergencia",       _A),
    "com.android.smspush":                          KnownPackage("SMS push",                    _A),
    "com.android.vending":                          KnownPackage("Play Store",                  _G),
    "com.android.chrome":                           KnownPackage("Chrome",                      _G),
    "com.android.keyguard":                         KnownPackage("Pantalla de bloqueo",         _A),
    "com.android.cts.priv.ctsshim":                KnownPackage("CTS shim",                    _A),
    "com.android.overlay":                          KnownPackage("Overlays del sistema",        _A),
    "com.android.internal.display":                 KnownPackage("Display interno",             _A),
    "com.android.networkstack":                     KnownPackage("Pila de red Android",         _A),

    # ─── Sistema Xiaomi / MIUI / HyperOS ─────────────────────────────────────
    "com.miui.home":                                KnownPackage("Launcher HyperOS",            _X),
    "com.miui.securitycenter":                      KnownPackage("Seguridad MIUI",              _X),
    "com.miui.cleanmaster":                         KnownPackage("Limpiador MIUI",              _X),
    "com.miui.analytics":                           KnownPackage("Analíticas MIUI",             _X),
    "com.miui.msa.global":                          KnownPackage("Sistema de anuncios MIUI",    _X),
    "com.miui.systemAdSolution":                    KnownPackage("Anuncios MIUI",               _X),
    "com.miui.daemon":                              KnownPackage("Demonio MIUI",                _X),
    "com.miui.AnalyticsCore":                       KnownPackage("Core analítico MIUI",         _X),
    "com.miui.hybrid":                              KnownPackage("WebView MIUI",                _X),
    "com.miui.cloudservice":                        KnownPackage("Nube Mi",                     _X),
    "com.miui.cloudbackup":                         KnownPackage("Backup nube Mi",              _X),
    "com.miui.weather":                             KnownPackage("Clima Xiaomi",                _X),
    "com.miui.videoplayer":                         KnownPackage("Reproductor de video Mi",     _X),
    "com.miui.player":                              KnownPackage("Música Mi",                   _X),
    "com.miui.notes":                               KnownPackage("Notas Mi",                    _X),
    "com.miui.calculator":                          KnownPackage("Calculadora Mi",              _X),
    "com.miui.compass":                             KnownPackage("Brújula Mi",                  _X),
    "com.miui.yellowpage":                          KnownPackage("Páginas amarillas Mi",        _X),
    "com.miui.powerkeeper":                         KnownPackage("PowerKeeper Mi",              _X),
    "com.miui.personalassistant":                   KnownPackage("Asistente personal Mi",       _X),
    "com.miui.mishare.connectivity":                KnownPackage("Mi Share",                    _X),
    "com.miui.gallery":                             KnownPackage("Galería Mi",                  _X),
    "com.miui.backup":                              KnownPackage("Backup Mi",                   _X),
    "com.miui.screenrecorder":                      KnownPackage("Grabador de pantalla",        _X),
    "com.miui.bugreport":                           KnownPackage("Reporte de errores",          _X),
    "com.miui.fm":                                  KnownPackage("Radio FM",                    _X),
    "com.miui.qr":                                  KnownPackage("Escáner QR Mi",               _X),
    "com.miui.contentextension":                    KnownPackage("Extensión de contenido",      _X),
    "com.miui.faceunlock":                          KnownPackage("Desbloqueo facial Mi",        _X),
    "com.miui.gamebooster":                         KnownPackage("Game Booster Mi",             _X),
    "com.miui.greenguard":                          KnownPackage("Green Guard Mi",              _X),
    "com.miui.keyboard":                            KnownPackage("Teclado Mi",                  _X),
    "com.miui.micanvas":                            KnownPackage("Mi Canvas",                   _X),
    "com.miui.mipicks":                             KnownPackage("GetApps",                     _X),
    "com.miui.mistore":                             KnownPackage("Mi Store",                    _X),
    "com.miui.misupport":                           KnownPackage("Soporte Mi",                  _X),
    "com.miui.smarthome":                           KnownPackage("Smart Home Mi",               _X),
    "com.miui.touch":                               KnownPackage("Gestos MIUI",                 _X),
    "com.miui.translation":                         KnownPackage("Traducción Mi",               _X),
    "com.miui.userguide":                           KnownPackage("Guía de usuario Mi",          _X),
    "com.miui.voiceassist":                         KnownPackage("Asistente de voz Mi",        _X),
    "com.miui.vsimcore":                            KnownPackage("vSIM Mi",                     _X),
    "com.miui.rome":                                KnownPackage("Servicio Rome (backup)",       _X),
    "com.miui.audiomonitor":                        KnownPackage("Monitor de audio",            _X),
    "com.miui.extraphoto":                          KnownPackage("Extra Photo Mi",              _X),
    "com.miui.lazylunch":                           KnownPackage("LazyLunch MIUI",              _X),
    "com.miui.micreditservice":                     KnownPackage("Servicio crédito Mi",         _X),
    "com.miui.mifocus":                             KnownPackage("Mi Focus",                    _X),
    "com.miui.migamepad":                           KnownPackage("Mi Gamepad",                  _X),
    "com.miui.milinkservice":                       KnownPackage("Mi Link",                     _X),
    "com.miui.superresolution":                     KnownPackage("Super resolución Mi",         _X),
    "com.miui.system":                              KnownPackage("Sistema MIUI",                _X),
    "com.miui.systemui.plugin":                     KnownPackage("Plugin System UI Mi",         _X),
    "com.miui.tsmclient":                           KnownPackage("TSM Client Mi",               _X),
    "com.miui.virtualsim":                          KnownPackage("SIM Virtual Mi",              _X),
    "com.miui.wmsvc":                               KnownPackage("Servicio WM Mi",              _X),
    "com.miui.xspace":                              KnownPackage("XSpace (multi-espacio)",      _X),
    "com.miui.findmyphone":                         KnownPackage("Encontrar mi teléfono",       _X),
    "com.miui.aod":                                 KnownPackage("Always On Display",           _X),
    "com.miui.global.providers":                    KnownPackage("Proveedores globales Mi",     _X),
    "com.miui.providers.contacts":                  KnownPackage("Contactos MIUI",              _X),
    "com.miui.networkassistant":                    KnownPackage("Asistente de red Mi",         _X),
    "com.miui.antivirus":                           KnownPackage("Antivirus MIUI",              _X),
    "com.miui.miservice":                           KnownPackage("Servicio Mi",                 _X),
    "com.miui.mipay.miservice":                     KnownPackage("Servicio Mi Pay",             _X),

    "com.xiaomi.account":                           KnownPackage("Cuenta Xiaomi",               _X),
    "com.xiaomi.airpods":                           KnownPackage("AirPods Xiaomi",              _X),
    "com.xiaomi.bluetooth":                         KnownPackage("Bluetooth Xiaomi",            _X),
    "com.xiaomi.drivemode":                         KnownPackage("Modo conductor Xiaomi",       _X),
    "com.xiaomi.finddevice":                        KnownPackage("Encontrar dispositivo",       _X),
    "com.xiaomi.gamecenter":                        KnownPackage("Centro de juegos",            _X),
    "com.xiaomi.joyose":                            KnownPackage("Gestión térmica (CRÍTICO)",   _X),
    "com.xiaomi.market":                            KnownPackage("Mi Market",                   _X),
    "com.xiaomi.mibrain":                           KnownPackage("Mi Brain",                    _X),
    "com.xiaomi.micloud.sdk":                       KnownPackage("SDK Nube Mi",                 _X),
    "com.xiaomi.mirrorservice":                     KnownPackage("Espejo Mi",                   _X),
    "com.xiaomi.misettings":                        KnownPackage("Ajustes Mi",                  _X),
    "com.xiaomi.miwifi":                            KnownPackage("Mi WiFi",                     _X),
    "com.xiaomi.payment":                           KnownPackage("Mi Pay",                      _X),
    "com.xiaomi.router":                            KnownPackage("Router Mi",                   _X),
    "com.xiaomi.scanner":                           KnownPackage("Escáner Mi",                  _X),
    "com.xiaomi.simactivate.service":               KnownPackage("Activación SIM Xiaomi",       _X),
    "com.xiaomi.smarthome":                         KnownPackage("Smart Home Xiaomi",           _X),
    "com.xiaomi.smarthomekit":                      KnownPackage("Kit Smart Home Mi",           _X),
    "com.xiaomi.wearable":                          KnownPackage("Wearables Mi",                _X),
    "com.xiaomi.xmsf":                              KnownPackage("Servicio XMSF",               _X),
    "com.xiaomi.youpin":                            KnownPackage("Youpin",                      _X),
    "com.xiaomi.glgm":                              KnownPackage("GLGM Xiaomi",                 _X),
    "com.xiaomi.joyose.helio":                      KnownPackage("Helio Thermal (CRÍTICO)",     _X),

    # ─── Google ──────────────────────────────────────────────────────────────
    "com.google.android.gms":                       KnownPackage("Google Play Services",        _G),
    "com.google.android.gsf":                       KnownPackage("Marco Servicios Google",      _G),
    "com.google.android.play.games":                KnownPackage("Google Play Games",           _G),
    "com.google.android.youtube":                   KnownPackage("YouTube",                     _G),
    "com.google.android.apps.youtube.music":        KnownPackage("YouTube Music",               _G),
    "com.google.android.apps.maps":                 KnownPackage("Google Maps",                 _G),
    "com.google.android.gm":                        KnownPackage("Gmail",                       _G),
    "com.google.android.apps.photos":               KnownPackage("Google Fotos",                _G),
    "com.google.android.videos":                    KnownPackage("Google TV",                   _G),
    "com.google.android.apps.tachyon":              KnownPackage("Google Meet",                 _G),
    "com.google.android.talk":                      KnownPackage("Google Chat",                 _G),
    "com.google.android.inputmethod.latin":         KnownPackage("Gboard",                      _G),
    "com.google.android.apps.chromecast.app":       KnownPackage("Google Home",                 _G),
    "com.google.android.apps.subscriptions.red":    KnownPackage("Google One",                  _G),
    "com.google.android.marvin.talkback":           KnownPackage("TalkBack",                    _G),
    "com.google.android.calendar":                  KnownPackage("Google Calendar",             _G),
    "com.google.android.contacts":                  KnownPackage("Google Contactos",            _G),
    "com.google.android.deskclock":                 KnownPackage("Google Reloj",                _G),
    "com.google.android.dialer":                    KnownPackage("Google Teléfono",             _G),
    "com.google.android.feedback":                  KnownPackage("Feedback de Google",          _G),
    "com.google.android.keep":                      KnownPackage("Google Keep",                 _G),
    "com.google.android.googlequicksearchbox":      KnownPackage("Búsqueda de Google",          _G),
    "com.google.android.partnersetup":              KnownPackage("Configuración de socio",      _G),
    "com.google.android.tts":                       KnownPackage("Texto a voz Google",          _G),
    "com.google.android.webview":                   KnownPackage("WebView de Android",          _G),
    "com.google.android.apps.wellbeing":            KnownPackage("Bienestar digital",           _G),
    "com.google.android.configupdater":             KnownPackage("Actualizador de config",      _G),
    "com.google.android.as":                        KnownPackage("Android System Intelligence", _G),
    "com.google.android.as.oss":                    KnownPackage("Private Compute Core",        _G),
    "com.google.android.sdksandbox":                KnownPackage("SDK Sandbox",                 _G),
    "com.google.android.permissioncontroller":      KnownPackage("Permisos Google",             _G),
    "com.google.android.cellbroadcastreceiver":     KnownPackage("Alertas celulares Google",    _G),
    "com.google.android.wifi.resources":            KnownPackage("Recursos WiFi Google",        _G),
    "com.google.android.healthconnect.controller":  KnownPackage("Health Connect",              _G),
    "com.google.android.nearby":                    KnownPackage("Nearby Share Google",         _G),
    "com.google.android.networkstack":              KnownPackage("Pila de red Google",          _G),
    "com.google.android.connectivity.subscriberidentity": KnownPackage("Identidad suscriptor",  _G),
    "com.google.android.uwb":                       KnownPackage("Ultra Wideband",              _G),
    "com.google.android.apps.restore":              KnownPackage("Google Restore",              _G),
    "com.google.android.apps.turbo":                KnownPackage("Device Health Services",      _G),
    "com.google.ar.core":                           KnownPackage("AR Core",                     _G),
    "com.google.android.printservice.recommendation": KnownPackage("Servicio impresión Google", _G),
    "com.google.android.apps.docs":                 KnownPackage("Google Docs",                 _G),
    "com.google.android.apps.sheets":               KnownPackage("Google Sheets",               _G),
    "com.google.android.apps.slides":               KnownPackage("Google Slides",               _G),
    "com.google.android.apps.drive":                KnownPackage("Google Drive",                _G),
    "com.google.android.syncadapters.calendar":     KnownPackage("Sync calendario Google",      _G),
    "com.google.android.syncadapters.contacts":     KnownPackage("Sync contactos Google",       _G),
    "com.google.android.gsf.login":                 KnownPackage("Login GSF",                   _G),
    "com.google.android.instantapps":               KnownPackage("Instant Apps",                _G),
    "com.google.android.apps.classroom":            KnownPackage("Google Classroom",            _G),
    "com.google.android.apps.translate":            KnownPackage("Google Translate",            _G),
    "com.google.android.apps.nbu.files":            KnownPackage("Files by Google",             _G),
    "com.google.android.apps.nbu.paisa.user":       KnownPackage("Google Pay",                  _G),
    "com.google.android.apps.youtube.creator":      KnownPackage("YouTube Studio",              _G),
    "com.google.android.documentsui":               KnownPackage("Documentos UI Google",        _G),
    "com.google.android.ext.shared":                KnownPackage("Extensiones Google",          _G),
    "com.google.android.overlay.gmsconfig":         KnownPackage("Config GMS",                  _G),
    "com.google.android.gmsintegration":            KnownPackage("Integración GMS",             _G),
    "com.google.android.apps.safetyhub":            KnownPackage("Safety Hub Google",           _G),

    # ─── Redes sociales ──────────────────────────────────────────────────────
    "com.facebook.katana":                          KnownPackage("Facebook",                    _S),
    "com.facebook.orca":                            KnownPackage("Messenger",                   _S),
    "com.facebook.lite":                            KnownPackage("Facebook Lite",               _S),
    "com.facebook.services":                        KnownPackage("Servicios Facebook",          _S),
    "com.facebook.system":                          KnownPackage("Sistema Facebook",            _S),
    "com.instagram.android":                        KnownPackage("Instagram",                   _S),
    "com.whatsapp":                                 KnownPackage("WhatsApp",                    _C),
    "com.whatsapp.w4b":                             KnownPackage("WhatsApp Business",           _C),
    "com.zhiliaoapp.musically":                     KnownPackage("TikTok",                      _S),
    "com.ss.android.ugc.trill":                     KnownPackage("TikTok (regional)",           _S),
    "com.twitter.android":                          KnownPackage("X (Twitter)",                 _S),
    "com.snapchat.android":                         KnownPackage("Snapchat",                    _S),
    "org.telegram.messenger":                       KnownPackage("Telegram",                    _C),
    "com.discord":                                  KnownPackage("Discord",                     _C),
    "com.reddit.frontpage":                         KnownPackage("Reddit",                      _S),
    "com.pinterest":                                KnownPackage("Pinterest",                   _S),
    "com.linkedin.android":                         KnownPackage("LinkedIn",                    _S),
    "com.tumblr":                                   KnownPackage("Tumblr",                      _S),
    "com.vkontakte.android":                        KnownPackage("VKontakte",                   _S),
    "com.bereal.android":                           KnownPackage("BeReal",                      _S),
    "com.threads.android":                          KnownPackage("Threads",                     _S),
    "com.meetup.android":                           KnownPackage("Meetup",                      _S),
    "com.twitch.android.app":                       KnownPackage("Twitch",                      _E),
    "tv.twitch.android.app":                        KnownPackage("Twitch",                      _E),

    # ─── Comunicación ────────────────────────────────────────────────────────
    "com.skype.raider":                             KnownPackage("Skype",                       _C),
    "com.viber.voip":                               KnownPackage("Viber",                       _C),
    "org.thoughtcrime.securesms":                   KnownPackage("Signal",                      _C),
    "com.microsoft.teams":                          KnownPackage("Microsoft Teams",             _P),
    "com.slack":                                    KnownPackage("Slack",                       _P),
    "us.zoom.videomeetings":                        KnownPackage("Zoom",                        _C),
    "com.zoom.videomeetings":                       KnownPackage("Zoom",                        _C),
    "com.wire.android":                             KnownPackage("Wire",                        _C),
    "com.google.android.apps.messaging":            KnownPackage("Mensajes Google",             _C),
    "com.microsoft.launcher":                       KnownPackage("Microsoft Launcher",          _P),

    # ─── Entretenimiento ─────────────────────────────────────────────────────
    "com.netflix.mediaclient":                      KnownPackage("Netflix",                     _E),
    "com.spotify.music":                            KnownPackage("Spotify",                     _E),
    "com.amazon.mShop.android.shopping":            KnownPackage("Amazon Shopping",             _E),
    "com.hbo.hbonow":                               KnownPackage("Max (HBO)",                   _E),
    "com.disneyplus":                               KnownPackage("Disney+",                     _E),
    "com.amazon.avod.thirdpartyclient":             KnownPackage("Amazon Prime Video",          _E),
    "com.crunchyroll.crunchyroid":                  KnownPackage("Crunchyroll",                 _E),
    "com.deezer.android":                           KnownPackage("Deezer",                      _E),
    "com.soundcloud.android":                       KnownPackage("SoundCloud",                  _E),
    "com.tidal.android":                            KnownPackage("TIDAL",                       _E),
    "com.plexapp.android":                          KnownPackage("Plex",                        _E),
    "com.shazam.android":                           KnownPackage("Shazam",                      _E),
    "com.apple.android.music":                      KnownPackage("Apple Music",                 _E),
    "com.google.android.apps.youtube.music":        KnownPackage("YouTube Music",               _E),
    "com.vanced.android.youtube":                   KnownPackage("Vanced YouTube",              _E),

    # ─── Productividad ───────────────────────────────────────────────────────
    "com.microsoft.office.word":                    KnownPackage("Microsoft Word",              _P),
    "com.microsoft.office.excel":                   KnownPackage("Microsoft Excel",             _P),
    "com.microsoft.office.powerpoint":              KnownPackage("Microsoft PowerPoint",        _P),
    "com.microsoft.office.outlook":                 KnownPackage("Microsoft Outlook",           _P),
    "com.microsoft.skydrive":                       KnownPackage("Microsoft OneDrive",          _P),
    "com.microsoft.bing":                           KnownPackage("Microsoft Bing",              _P),
    "com.microsoft.office.officehubrow":            KnownPackage("Microsoft Office Hub",        _P),
    "com.dropbox.android":                          KnownPackage("Dropbox",                     _P),
    "com.evernote":                                 KnownPackage("Evernote",                    _P),
    "com.adobe.reader":                             KnownPackage("Adobe Acrobat",               _P),
    "com.adobe.scan.android":                       KnownPackage("Adobe Scan",                  _P),
    "com.docusign.ink":                             KnownPackage("DocuSign",                    _P),
    "com.notion.id":                                KnownPackage("Notion",                      _P),
    "com.todoist.android":                          KnownPackage("Todoist",                     _P),
    "com.trello":                                   KnownPackage("Trello",                      _P),
    "com.atlassian.jira.for.android":               KnownPackage("Jira",                        _P),
    "com.asana.app":                                KnownPackage("Asana",                       _P),

    # ─── MediaTek (Helio G81 Ultra) ──────────────────────────────────────────
    "com.mediatek.batterywarning":                  KnownPackage("Advertencia batería MTK",     _M),
    "com.mediatek.bluetooth":                       KnownPackage("Bluetooth MTK",               _M),
    "com.mediatek.callrecorder":                    KnownPackage("Grabador llamadas MTK",       _M),
    "com.mediatek.dm":                              KnownPackage("DM MTK",                      _M),
    "com.mediatek.duraspeed":                       KnownPackage("DuraSpeed MTK",               _M),
    "com.mediatek.engineermode":                    KnownPackage("Modo ingeniero MTK",          _M),
    "com.mediatek.factorymode":                     KnownPackage("Modo fábrica MTK",            _M),
    "com.mediatek.gnsspwr":                         KnownPackage("GNSS Power MTK",              _M),
    "com.mediatek.lbs.em2.ui":                      KnownPackage("LBS EM UI MTK",               _M),
    "com.mediatek.mtklogger":                       KnownPackage("Logger MTK",                  _M),
    "com.mediatek.networklocation":                 KnownPackage("Ubicación red MTK",           _M),
    "com.mediatek.nfc":                             KnownPackage("NFC MTK",                     _M),
    "com.mediatek.omacp":                           KnownPackage("OMA CP MTK",                  _M),
    "com.mediatek.phone":                           KnownPackage("Teléfono MTK",                _M),
    "com.mediatek.rcs.app":                         KnownPackage("RCS MTK",                     _M),
    "com.mediatek.security":                        KnownPackage("Seguridad MTK",               _M),
    "com.mediatek.simprocessor":                    KnownPackage("Procesador SIM MTK",          _M),
    "com.mediatek.systemupdate":                    KnownPackage("Actualización sistema MTK",   _M),
    "com.mediatek.thermalmanager":                  KnownPackage("Gestor térmico MTK",          _M),
    "com.mediatek.wfo.impl":                        KnownPackage("WFO MTK",                     _M),
    "com.mediatek.wps":                             KnownPackage("WPS MTK",                     _M),
    "com.mediatek.location.lppe.main":              KnownPackage("Localización LPPE MTK",       _M),
    "com.mediatek.ims":                             KnownPackage("IMS MTK",                     _M),
    "com.mediatek.ygps":                            KnownPackage("GPS MTK",                     _M),
    "com.mediatek.voiceunlock":                     KnownPackage("Desbloqueo voz MTK",          _M),
    "com.mediatek.cameraunit":                      KnownPackage("Unidad cámara MTK",           _M),
    "com.mediatek.dataprotection":                  KnownPackage("Protección datos MTK",        _M),
}


def lookup(pkg: str) -> KnownPackage | None:
    return PACKAGES_DB.get(pkg)
